services:
  db:
    image: postgres:16
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo_db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: